name: publish to nuget
on: 
  workflow_dispatch
  #push:
    #branches:
      #- main
      
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps: 
    - name: Check out Repo
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Pack TwoFactorAuth
      run: dotnet pack src\\Our.Umbraco.TwoFactorAuth\\Our.Umbraco.TwoFactorAuth.csproj -c Release
    
    - name: Pack TwoFactorAuth Assets
      run: dotnet pack src\\Our.Umbraco.TwoFactorAuth.Assets\\Our.Umbraco.TwoFactorAuth.Assets.csproj -c Release
      
    - name: Publish TwoFactorAuth
      run: dotnet nuget push /home/runner/work/Our.Umbraco.TwoFactorAuth/Our.Umbraco.TwoFactorAuth/src/Our.Umbraco.TwoFactorAuth/bin/Release/Our.Umbraco.TwoFactorAuth.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Publish TwoFactorAuth Assets
      run: dotnet nuget push /home/runner/work/Our.Umbraco.TwoFactorAuth.Assets/Our.Umbraco.TwoFactorAuth.Assets/src/Our.Umbraco.TwoFactorAuth.Assets/bin/Release/Our.Umbraco.TwoFactorAuth.Assets.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
