name: publish to nuget
on: 
  workflow_dispatch
  #push:
    #branches:
      #- main
      
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps: 
    - name: Check out Repo
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Pack
      run: dotnet pack src\\Our.Umbraco.TwoFactorAuth\\Our.Umbraco.TwoFactorAuth.csproj -c Release
      
    - name: Publish to GitHub packages 
      run: dotnet nuget push /home/runner/work/Our.Umbraco.TwoFactorAuth/Our.Umbraco.TwoFactorAuth/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate`
